---
- name: Clear vm hosts log
  gather_facts: no
  hosts: vm
  tasks:
    - name: journalctl 50mb
      ansible.builtin.shell:
        cmd: command -v journalctl > /dev/null && journalctl --vacuum-size=50M || true  

    - name: rm log_gz
      ansible.builtin.shell:
        cmd: rm -rf /var/log/*.gz

    - name: rm log_1-9
      ansible.builtin.shell:
        cmd: rm -rf /var/log/*.[0-9]

    - name: rm nginx_log_1_9
      ansible.builtin.shell:
        cmd: test -d "/var/log/nginx" && rm -rf /var/log/nginx/*.[0-9] && rm -rf /var/log/nginx/*.gz || true

    - name: rm apt_log_gz
      ansible.builtin.shell:
        cmd: test -d "/var/log/apt" && rm -rf /var/log/apt/*.gz || true

    - name: rm samba_log_gz
      ansible.builtin.shell:
        cmd: test -d "/var/log/samba" && rm -rf /var/log/samba/*.gz || true

    - name: rm redis_log_gz
      ansible.builtin.shell:
        cmd: test -d "/var/log/redis" && rm -rf /var/log/redis/*.gz || true

    - name: show file list
      ansible.builtin.shell:
        cmd: command -v tree > /dev/null && tree -L 2 /var/log || ls /var/log
      register: file_list

    - name: Clear log result
      debug:
        msg:
          file_list: "{{ file_list.stdout.split('\n') }}"

- name: Clear lxc log
  gather_facts: no
  hosts: lxc
  connection: local
  tasks:
    - name: journalctl 50mb
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "command -v journalctl > /dev/null && journalctl --vacuum-size=50M || true"
    
    - name: rm log_gz
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "rm -rf /var/log/*.gz"

    - name: rm log_1-9
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "rm -rf /var/log/*.[0-9]"

    - name: rm nginx_log_1_9
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: 'test -d "/var/log/nginx" && rm -rf /var/log/nginx/*.[0-9] || true'

    - name: rm apt_log_gz
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: 'test -d "/var/log/apt" && rm -rf /var/log/apt/*.gz || true'

    - name: rm samba_log_gz
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: 'test -d "/var/log/samba" && rm -rf /var/log/samba/*.gz || true'

    - name: rm redis_log_gz
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: 'test -d "/var/log/redis" && rm -rf /var/log/redis/*.gz || true'

    - name: show file list
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "command -v tree > /dev/null && tree -L 2 /var/log || ls /var/log"
      register: file_list

    - name: Clear log result
      debug:
        msg:
          update: "{{ file_list.output.split('\n') }}"