- name: Get os type
  gather_facts: no
  hosts: vm
  tasks:
    - name: Get os type
      shell: "sh -c 'cat /etc/os-release'"
      #command: cat /etc/os-release
      register: os_type

    - name: Print os type
      debug:
        msg: "{{ os_type.stdout_lines }}"

- name: Get os type
  gather_facts: no
  hosts: lxc
  connection: local
  tasks:
    - name: Get os type
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: cat /etc/os-release
      register: os_type

    - name: Print os type
      debug:
        msg: "{{ os_type.output_lines }}"
