- name: Get os type
  gather_facts: no
  hosts: vm
  tasks:
    - name: Get os type
      shell: bash -c 'source /etc/os-release && echo $ID-$VERSION_ID'
      register: os_type

    - name: Print os type
      debug:
        msg: "{{ os_type.stdout }}"

- name: Get os type
  gather_facts: no
  hosts: lxc
  connection: local
  tasks:
    - name: Get os type
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: source /etc/os-release && echo $ID-$VERSION_ID
      register: os_type

    - name: Print os type
      debug:
        msg: "{{ os_type.output }}"