# update.yml
---
- name: Upadte vm hosts
  gather_facts: no
  hosts: vm
  tasks:
    - name: Create a temporary directory
      shell: mktemp -d
      register: temp_dir

    - name: Push update.sh
      copy:
        src: "./scripts/update.sh"
        dest: "{{ temp_dir.stdout }}/update.sh"

    - name: Chmod update.sh
      shell: chmod +x "{{ temp_dir.stdout }}/update.sh"

    - name: Exec update.sh
      shell: "{{ temp_dir.stdout }}/update.sh"

    - name: Clean
      shell: rm -rf "{{ temp_dir.stdout }}"

- name: Run script on LXC hosts
  gather_facts: no
  hosts: lxc
  connection: local
  tasks:
    - name: Create a temporary directory on LXC
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "mktemp -d"
      register: temp_dir

    - name: Push update.sh
      pct:
        cmd: "push"
        host: "{{ inventory_hostname }}"
        src: "./scripts/update.sh"
        dest: "{{ temp_dir.output }}/update.sh"

    - name: Chmod update.sh
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "chmod +x {{ temp_dir.output }}/update.sh"

    - name: Exec update.sh
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "{{ temp_dir.output }}/update.sh"

    - name: Clean
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "rm -rf {{ temp_dir.output }}"
