# update.yml
---
- name: Upadte vm hosts
  gather_facts: no
  hosts: vm
  tasks:
    - name: Create a temporary directory
      shell: mktemp -d
      register: temp_dir

    - name: Push update.sh
      copy:
        src: "./scripts/update.sh"
        dest: "{{ temp_dir.stdout }}/update.sh"
        mode: '0755'

    - name: Exec update.sh
      shell: "{{ temp_dir.stdout }}/update.sh"
      register: result

    - name: Clean
      shell: rm -rf "{{ temp_dir.stdout }}"

    - name: Check result
      debug:
        msg: "{{ result.stdout.split('\n') }}"

- name: Run script on LXC hosts
  gather_facts: no
  hosts: lxc
  connection: local
  tasks:
    - name: Create a temporary directory on LXC
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "mktemp -d"
      register: temp_dir

    - name: Push update.sh
      pct:
        cmd: "push"
        host: "{{ inventory_hostname }}"
        src: "./scripts/update.sh"
        dest: "{{ temp_dir.output }}/update.sh"
        extra_args: "--perms 0755"

    - name: Exec update.sh
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "{{ temp_dir.output }}/update.sh"
      register: result

    - name: Clean
      pct:
        cmd: "exec"
        host: "{{ inventory_hostname }}"
        extra_args: "rm -rf {{ temp_dir.output }}"

    - name: Check result
      debug:
        msg: "{{ result.output.split('\n') }}"
